## 宿題 6.5 ：Numpy ミニ演習 np.append()
(1) Python のリスト [0, 1, 2, 3, 4] への末尾に要素 [5] を追加しなさい。

(2) Numpy 配列 [0, 1, 2, 3, 4] の末尾に配列 [5, 6] を追加して、配列[1, 2, 3, 4, 5, 6]] を作りなさい。

（ヒント：python の append() と np.append() を使う）

In [1]:
import numpy as np

In [5]:
lst = [0,1,2,3,4]
lst

[0, 1, 2, 3, 4]

In [6]:
lst.append(5)
lst

[0, 1, 2, 3, 4, 5]

In [9]:
lst2 = np.array([0,1,2,3,4])
lst2

array([0, 1, 2, 3, 4])

In [15]:
lst3 = np.append(lst2, [5,6])
lst3

array([0, 1, 2, 3, 4, 5, 6])

In [16]:
print(lst2)
print(lst3)

[0 1 2 3 4]
[0 1 2 3 4 5 6]
