## 宿題６：Numpy の演習
(1) 「pulsar_stars.csv」をデータフレームとして読み込み、データを四捨五入しなさい。

(2) 四捨五入したデータを整数にしなさい。

(3)  「pulsar_stars.csv」をデータフレームとして読み込み、numpy配列にしなさい。

(4) その配列の要素を四捨五入しなさい。

(5) その配列の要素を整数にしなさい。

(6) 「pulsar_stars.csv」を numpy配列として読み込みなさい。

(7) その numpy配列を「*.npy」として保存し、再度読み込み配列を表示しなさい。

In [2]:
import numpy as np
import pandas as pd

(1) 「pulsar_stars.csv」をデータフレームとして読み込み、データを四捨五入しなさい。

In [3]:
# Pandas でCSVを読み込む
df = pd.read_csv("pulsar_stars.csv")
df.head()

Mean of the integrated profile  \
0                       140.562500   
1                       102.507812   
2                       103.015625   
3                       136.750000   
4                        88.726562   

    Standard deviation of the integrated profile  \
0                                      55.683782   
1                                      58.882430   
2                                      39.341649   
3                                      57.178449   
4                                      40.672225   

    Excess kurtosis of the integrated profile  \
0                                   -0.234571   
1                                    0.465318   
2                                    0.323328   
3                                   -0.068415   
4                                    0.600866   

    Skewness of the integrated profile   Mean of the DM-SNR curve  \
0                            -0.699648                   3.199833   
1                            -0.515088                   1.677258   
2                             1.051164                   3.121237   
3                            -0.636238                   3.642977   
4                             1.123492                   1.178930   

    Standard deviation of the DM-SNR curve  \
0                                19.110426   
1                                14.860146   
2                                21.744669   
3                                20.959280   
4                                11.468720   

    Excess kurtosis of the DM-SNR curve   Skewness of the DM-SNR curve  \
0                              7.975532                      74.242225   
1                             10.576487                     127.393580   
2                              7.735822                      63.171909   
3                              6.896499                      53.593661   
4                             14.269573                     252.567306   

   target_class  
0             0  
1             0  
2             0  
3             0  
4             0

In [3]:
df.shape

(17898, 9)

In [4]:
# 要素を四捨五入する
df_rd = df.round()
df_rd.head()

Mean of the integrated profile  \
0                            141.0   
1                            103.0   
2                            103.0   
3                            137.0   
4                             89.0   

    Standard deviation of the integrated profile  \
0                                           56.0   
1                                           59.0   
2                                           39.0   
3                                           57.0   
4                                           41.0   

    Excess kurtosis of the integrated profile  \
0                                        -0.0   
1                                         0.0   
2                                         0.0   
3                                        -0.0   
4                                         1.0   

    Skewness of the integrated profile   Mean of the DM-SNR curve  \
0                                 -1.0                        3.0   
1                                 -1.0                        2.0   
2                                  1.0                        3.0   
3                                 -1.0                        4.0   
4                                  1.0                        1.0   

    Standard deviation of the DM-SNR curve  \
0                                     19.0   
1                                     15.0   
2                                     22.0   
3                                     21.0   
4                                     11.0   

    Excess kurtosis of the DM-SNR curve   Skewness of the DM-SNR curve  \
0                                   8.0                           74.0   
1                                  11.0                          127.0   
2                                   8.0                           63.0   
3                                   7.0                           54.0   
4                                  14.0                          253.0   

   target_class  
0             0  
1             0  
2             0  
3             0  
4             0

(2) 四捨五入したデータを整数にしなさい。

In [6]:
# 要素を整数にキャストする
df_rd.astype(int).head()

Mean of the integrated profile  \
0                              141   
1                              103   
2                              103   
3                              137   
4                               89   

    Standard deviation of the integrated profile  \
0                                             56   
1                                             59   
2                                             39   
3                                             57   
4                                             41   

    Excess kurtosis of the integrated profile  \
0                                           0   
1                                           0   
2                                           0   
3                                           0   
4                                           1   

    Skewness of the integrated profile   Mean of the DM-SNR curve  \
0                                   -1                          3   
1                                   -1                          2   
2                                    1                          3   
3                                   -1                          4   
4                                    1                          1   

    Standard deviation of the DM-SNR curve  \
0                                       19   
1                                       15   
2                                       22   
3                                       21   
4                                       11   

    Excess kurtosis of the DM-SNR curve   Skewness of the DM-SNR curve  \
0                                     8                             74   
1                                    11                            127   
2                                     8                             63   
3                                     7                             54   
4                                    14                            253   

   target_class  
0             0  
1             0  
2             0  
3             0  
4             0

(3) 「pulsar_stars.csv」をデータフレームとして読み込み、numpy配列にしなさい。

In [7]:
# データフレームをnumpy配列に変換
arr = np.array(df)
arr

array([[140.5625    ,  55.68378214,  -0.23457141, ...,   7.97553179,
         74.24222492,   0.        ],
       [102.5078125 ,  58.88243001,   0.46531815, ...,  10.57648674,
        127.3935796 ,   0.        ],
       [103.015625  ,  39.34164944,   0.32332837, ...,   7.73582202,
         63.17190911,   0.        ],
       ...,
       [119.3359375 ,  59.93593941,   0.1593631 , ...,   2.49951714,
          4.59517265,   0.        ],
       [114.5078125 ,  53.90239966,   0.20116138, ...,  10.00796731,
        134.2389095 ,   0.        ],
       [ 57.0625    ,  85.79734025,   1.40639105, ...,  -1.59752658,
          1.42947536,   0.        ]])

In [7]:
arr.shape

(17898, 9)

(4) その配列の要素を四捨五入しなさい。

In [8]:
# numpy配列の要素を四捨五入する
arr_rd = np.round(array)
arr_rd

array([[141.,  56.,  -0., ...,   8.,  74.,   0.],
       [103.,  59.,   0., ...,  11., 127.,   0.],
       [103.,  39.,   0., ...,   8.,  63.,   0.],
       ...,
       [119.,  60.,   0., ...,   2.,   5.,   0.],
       [115.,  54.,   0., ...,  10., 134.,   0.],
       [ 57.,  86.,   1., ...,  -2.,   1.,   0.]])

(5) その配列の要素を整数にしなさい。

In [10]:
# numpy配列の要素を整数にキャストする
arr_rd.astype(int)

array([[141,  56,   0, ...,   8,  74,   0],
       [103,  59,   0, ...,  11, 127,   0],
       [103,  39,   0, ...,   8,  63,   0],
       ...,
       [119,  60,   0, ...,   2,   5,   0],
       [115,  54,   0, ...,  10, 134,   0],
       [ 57,  86,   1, ...,  -2,   1,   0]])

(6) 「pulsar_stars.csv」を numpy配列として読み込みなさい。

In [16]:
# numpy で CSVファイルを読み込む方法
# 注：最初の行をスキップする
arr = np.loadtxt('pulsar_stars.csv', delimiter=',',skiprows=1)
arr

array([[140.5625    ,  55.68378214,  -0.23457141, ...,   7.97553179,
         74.24222492,   0.        ],
       [102.5078125 ,  58.88243001,   0.46531815, ...,  10.57648674,
        127.3935796 ,   0.        ],
       [103.015625  ,  39.34164944,   0.32332837, ...,   7.73582202,
         63.17190911,   0.        ],
       ...,
       [119.3359375 ,  59.93593941,   0.1593631 , ...,   2.49951714,
          4.59517265,   0.        ],
       [114.5078125 ,  53.90239966,   0.20116138, ...,  10.00796731,
        134.2389095 ,   0.        ],
       [ 57.0625    ,  85.79734025,   1.40639105, ...,  -1.59752658,
          1.42947536,   0.        ]])

(7) その numpy配列を「*.npy」として保存し、再度読み込み配列を表示しなさい。

In [20]:
# numpyデータの保存
np.save("arr",arr)

In [24]:
# *.npy ファイルの読み込み
arr = np.load("arr.npy")
arr

array([[140.5625    ,  55.68378214,  -0.23457141, ...,   7.97553179,
         74.24222492,   0.        ],
       [102.5078125 ,  58.88243001,   0.46531815, ...,  10.57648674,
        127.3935796 ,   0.        ],
       [103.015625  ,  39.34164944,   0.32332837, ...,   7.73582202,
         63.17190911,   0.        ],
       ...,
       [119.3359375 ,  59.93593941,   0.1593631 , ...,   2.49951714,
          4.59517265,   0.        ],
       [114.5078125 ,  53.90239966,   0.20116138, ...,  10.00796731,
        134.2389095 ,   0.        ],
       [ 57.0625    ,  85.79734025,   1.40639105, ...,  -1.59752658,
          1.42947536,   0.        ]])